# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "IAM.Messages.User" do
      optional :id, :int64, 1
    end
    add_message "IAM.Messages.User.Created" do
      optional :user, :message, 1, "IAM.Messages.User"
      optional :email, :string, 2
      optional :account_id, :int64, 3
    end
    add_message "IAM.Messages.User.Sync" do
      optional :user, :message, 1, "IAM.Messages.User"
    end
    add_message "IAM.Messages.User.Synced" do
      optional :user, :message, 1, "IAM.Messages.User"
    end
  end
end

module IAM
  module Messages
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IAM.Messages.User").msgclass
    User::Created = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IAM.Messages.User.Created").msgclass
    User::Sync = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IAM.Messages.User.Sync").msgclass
    User::Synced = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IAM.Messages.User.Synced").msgclass
  end
end
