# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "messages.IAM.User" do
      optional :id, :int64, 1
    end
    add_message "messages.IAM.User.Created" do
      optional :user, :message, 1, "messages.IAM.User"
      optional :email, :string, 2
      optional :account_id, :int64, 3
    end
    add_message "messages.IAM.User.Sync" do
      optional :user, :message, 1, "messages.IAM.User"
    end
    add_message "messages.IAM.User.Synced" do
      optional :user, :message, 1, "messages.IAM.User"
    end
  end
end

module Messages
  module IAM
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.IAM.User").msgclass
    User::Created = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.IAM.User.Created").msgclass
    User::Sync = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.IAM.User.Sync").msgclass
    User::Synced = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.IAM.User.Synced").msgclass
  end
end
